### ISSUE TITLE
Show hidden checkbox not playing well with others

### ISSUE THREAD

**Issue by nancikennedy** [ketho-wow/HideAppearance#2]
The checkbox on the collection page is obscuring/conflicting with other addons in its placement. For me, it's overlapping the sort list.

![hideappearances](https://user-images.githubusercontent.com/8207666/100494057-a138b880-30f2-11eb-81c2-e05cb475a5e8.PNG)

**Comment by Ketho** [comment]
Thanks, should be fixed now

**Comment by nancikennedy** [comment]
Sorry to say, it's also showing up in the transmog UI. Just noticed tonight.
![hidden appearances](https://user-images.githubusercontent.com/8207666/102611839-91eece80-40e4-11eb-82c0-222121924939.PNG)

**Comment by Ketho** [comment]
![image](https://user-images.githubusercontent.com/1073877/102659653-0e7fbc80-417a-11eb-91df-793a0d5f6190.png)
